	new gridjs.Grid({
  search: true,
  sort: true,
  pagination: {
   limit: 10
  },
  columns: ["Swaginan Nak Bali"],
  data: [
  ["Undagi = sebutan untuk orang yang bekerja sebagai tukang bagunan khas Bali"],
  ["Sangging = adalah orang yang bisa melakukan potong gigi saat upacara Mepandes || sebutan untuk mereka yang yang bisa membuat topeng, arca lukisan dan hal-hal berkaitan dengan pembuatan media suci di pura"],
  ["Dalang = sebutan untuk orang yang bisa menarikan wayang kulit"],
  ["Pregina = sebutan untuk penari Bali"],
  ["Bendega = sebutan untuk orang yang mencari ikan di Laut (nelayan)"],
  ["Pande =  sebutan untuk mereka yang bekerja sebagai pengerajin besi dalam membuat senjata"],
  ["Penabuh = sebutan untuk orang yang bisa memainkan gambelan"],
  ["Serati = sebutan untuk mereka yang di ahlikan sebagai pembuat banten (sesajen) ala Bali"],
  ["Guru Wisesa = sebutan untuk mereka yang bekerja di Pemerintahan"],
  ["Pekaseh = orang yang ditugaskan untuk mengawasi dan mengatur seluruh kegiatan yang berkaitan dengan sebuah organisasi Subak di Bali"],
  ["Guru Pengajian = sebutan untuk mereka yang bekerja mengajar di sekolah"],
  ["Bromocorah = orang yang suka melakukan atau berbuat jahat"],
  ["Prajuru Desa = sebutan untuk orang yang bertugas di desa Adat (Bali)"],
  ["Petajuh = sebutan untuk mereka yang bekerja melayani masyarakat desa adat"],
  ["Bendesa = petugas desa adat yang memiliki posisi teratas"],
  ["klian adat = petugas banjar adat"],
  ["klian tepekan = petugas tempekan adat atau dinas"],
  ["klian dinas = kepala Rw"],
  ["Saba Desa = adalah orang-orang yang diberikan tugas oleh anggota desa adat untuk memperhitungkan dan merencanakan seluruh kegiatan yang akan dilaksana dan terbaik untuk anggota masyarakat"],
  ["Adimuka --> Saba Desa"],
  ["Sinoman = orang yang memiliki tugas khusus di desa adat"],
  ["Pecalang = orang yang ditugaskan untuk menjaga keamaanan saat proses upacara keagamaan"],
  ["Seka Santi = adalah sebutan untuk anggota ataupun kelompok orang yang bertugas melantunkan kidung dan kekawin disaat upacara agama"],
  ["Botoh = sebutan untuk orang yang suka judi"],
  ["Saya = sebutan untuk orang yang mengatur dan mengelola saat penyelenggaran tajen (sabung ayam ala Bali)"],
  ["Tukang Kembar = sebutan untuk orang yang memegang/mengadu ayam di arena tajen"],
  ["Juru sapuh = petugas kebersihan di lingkungan desa adat atau banjar adat"],
  ["Jro Mangku = orang yang bertugas sebagai pemimpin upacara dalam hal doa yang dipilih dan dimiliki oleh setiap setiap desa adat dan sudah melaksanakan proses pawintenan eka jati"],
  ["Sulinggih Siwa = Pemimpin upacara di Bali yang memiliki kewenangan untuk menghaturkan yadnya (upacara dan upakara) dengan pesaksi sanggah surya, menyucikan Alam Atas dengan menurunkan kekuatan Sanghyang Widhi Wasa"],
  ["Sulinggih Buddha = pemimpin upacara di Bali yang memiliki kewenangan menghaturkan yadnya untuk menyucikan Alam Tengah (awang-awang) dengan mempertemukan kekuatan Sanghyang Widhi Wasa dengan kekuatan Bhuta Kala yang telah di Somia"],
  ["Sulinggih Bujangga = pemimpin upacara di Bali yang memiliki wewenang menghaturkan yadnya untuk membersihkan Alam Bawah(bumi beserta isinya)"],
  ["Pedanda = orang yang memiliki tugas memimpin upacara di Bali yang berasal dari trah Brahmana (dalam Catur Wangsa di Bali) yang sudah melukan proses diksa atau dwijati"],
  ["Pengiring = orang yang bertugas mengiringi sang Sulinggih"],
  ["Nabe = sebutan untuk orang yang menjadi guru dari Sang Sulinggih"],
  ["Dang Hyang = adalah sebutan bagi orang-orang yang sudah berjasa dalam pengembangan dan pelestarian ajaran Agama"],
  [" Rsi atau Bujangga =  pemimpin agama yang berasal dari golongan wangsa ksatria"],
  ["Empu = pemimpin Agama yang berasal dari trah Pasek dan Pande"],
  ["Sengguhu =  adalah orang yang bertugas dan ahli dalam tugas muput upacara Bhuta Yadnya"],
  ["Balian = orang yang memeliki kemampuan mengobati dengan cara spiritual"],
  ["Jro Dasaran = orang yang diberikan tugas dan mampu melakukan komunikasi dengan leluhur"],
  ["Tukang Apun = orang yang bekerja sebagai ahli pijat, baik itu hanya pijatan biasa ataupun mengobati masalah tulang"],
  ["Tukang Terang = orang yang memiliki tugas mengatur curah hujan dengan tekhik spiritual (pawang hujan)"],
  ["Pangiwa = orang yang melakukan dharmanya (bertugas menyeimbangkan energi semesta) dengan cara memutar energi ke arah Kiwa (kiri/ kebalik)"],
  ["Panengen = orang yang melakukan dharmanya (bertugas menyeimbangkan energi semesta) dengan cara memutar energi ke arah tengen (kanan/ searah)"],
  ]})
  .render(document.getElementById("tutlenc.blogspot.com/swagina"));
  document.write( '<br/><div style=\"text-align: center;\">created by: I Ketut Sunarta</div><div style=\"text-align: center;\"><a href=\"https://tutlenc.blogspot.com\"> © 2021 tutlencBlog</a></div>' );
